package util;

public enum Courses {
    INFORMATION_TECHNOLOGY,
    ELECTRICAL_ENGINEERING,
    AEROSPACE_ENGINEERING,
    BUSINESS_INFORMATICS,
    HUMAN_MEDICINE,
    EUROPEAN_LAW,
    MUSIC,
    ENVIRONMENTAL_SCIENCE,
    POLITICAL_SCIENCE
}
